# Generated by Django 3.2.6 on 2021-10-08 16:49

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallDetailRecord',
            fields=[
                ('outbound_cid', models.CharField(default='', max_length=80)),
                ('src', models.CharField(max_length=80)),
                ('dst', models.CharField(max_length=80)),
                ('diversion', models.CharField(default='', max_length=64)),
                ('channel', models.CharField(max_length=80)),
                ('dst_channel', models.CharField(max_length=80)),
                ('start', models.DateTimeField()),
                ('answer', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('duration', models.IntegerField(default=0)),
                ('billsec', models.IntegerField(default=0)),
                ('disposition', models.CharField(max_length=80)),
                ('uniquie_id', models.CharField(max_length=80)),
                ('pbx', models.CharField(default='', max_length=80)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Изначальный Список Звонков',
                'verbose_name_plural': 'Изначальный Список Звонков',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя компании')),
            ],
            options={
                'verbose_name': 'Компании',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя отдела')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Отделы',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', django.contrib.postgres.fields.ranges.BigIntegerRangeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='Отчество')),
                ('position', models.CharField(max_length=512, verbose_name='Должность')),
                ('work_number', models.CharField(max_length=32, verbose_name='Рабочий телефон (Asterisk код)')),
                ('additional_number', models.CharField(max_length=32, verbose_name='Дополнительный номер')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='CountedCallDetailRecord',
            fields=[
                ('outbound_cid', models.CharField(default='', max_length=80)),
                ('src', models.CharField(max_length=80)),
                ('dst', models.CharField(max_length=80)),
                ('diversion', models.CharField(default='', max_length=64)),
                ('channel', models.CharField(max_length=80)),
                ('dst_channel', models.CharField(max_length=80)),
                ('start', models.DateTimeField()),
                ('answer', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('duration', models.IntegerField(default=0)),
                ('billsec', models.IntegerField(default=0)),
                ('disposition', models.CharField(max_length=80)),
                ('uniquie_id', models.CharField(max_length=80)),
                ('pbx', models.CharField(default='', max_length=80)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Список Звонков',
                'verbose_name_plural': 'Список Звонков',
                'unique_together': {('uniquie_id', 'pbx')},
            },
        ),
    ]
